name: Release

on:
  push:
    branches:
      - main
    paths-ignore:   # prevent triggering when semantic-release commits changelog + version bump
      - "CHANGELOG.md"
      - "package.json"

permissions:
  contents: write
  issues: write
  pull-requests: write

jobs:
  release:
    if: github.actor != 'github-actions[bot]' # extra safeguard
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: pnpm

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Run semantic-release in release/next branch
        run: |
          git checkout -b release/next
          npx semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          branch: release/next
          base: main
          title: "chore: release"
          body: |
            This PR was automatically generated by semantic-release.

            - Updates version in package.json
            - Updates CHANGELOG.md
            - Adds release tag
          labels: release
          commit-message: "chore: release updates"
