name: Release

on:
  push:
    branches:
      - main
    paths-ignore: # prevent triggering when semantic-release commits changelog + version bump
      - 'CHANGELOG.md'
      - 'package.json'
      - 'pnpm-lock.yaml'

permissions:
  contents: write
  issues: write
  pull-requests: write

jobs:
  release:
    if: github.actor != 'github-actions[bot]' # extra safeguard
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: pnpm

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Run semantic-release
        id: semantic
        run: npx semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # Commit changes (changelog, version bump) to a PR instead of main
      - name: Create Release PR
        if: always()
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: 'chore(release): update changelog and bump version'
          branch: 'release/next'
          title: "ci(release): ${{steps.semantic.outputs.new_release_version || 'Update changelog'}}"
          body: 'This PR contains the release changes (CHANGELOG, version bump).'
          base: main
